/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "nbqiihyygojmgncyowet"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5icWlpaHl5Z29qbWduY3lvd2V0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjUyMTU2NzUsImV4cCI6MjA4MDc5MTY3NX0.5tLK4P-ErX-U3NQyge1tuphOgWtGCEVPkMs7VYhbqGw"